### PR TITLE
Credit Card Form refactor

### LINKED ISSUE #357: Credit card form errors break input labels
### Steps to reproduce the problem
1. Go through checkout to the Payment Method step.
2. Leave credit card fields empty and submit the form.

Labels are not rendered in the proper place and as a result, they clash with error messages.

### Screenshots
image

### PR DESCRIPTION
**Pull request by AlicjaSzu**
I want to merge this change because...

- [x] move CreditCardForm to @next and refactor

fix #357 

### Screenshots
Screenshot 2019-06-25 at 10 59 56

image

### Pull Request Checklist

1. [x] All visible strings are translated with proper context.
1. [x] All data-formatting is locale-aware (dates, numbers, and so on).
1. [x] The changes are tested.
1. [x] The code is documented (docstrings, project documentation).
1. [x] Changes are mentioned in the changelog.

### CODE REVIEW

File: src/@next/components/atoms/ErrorMessage/ErrorMessage.tsx [hunk 1]
```diff
@@ -4,8 +4,10 @@ import * as S from "./styles";
 import { IProps } from "./types";
 
 export const ErrorMessage: React.FC<IProps> = ({ errors }: IProps) =>
-  !!(errors && errors.length) && (
+  errors && errors.length ? (
```
Comment (jwm0) [inline src/@next/components/atoms/ErrorMessage/ErrorMessage.tsx]: Does it not work when you replace `?` with `&&`

File: src/@next/components/organisms/CreditCardForm/CreditCardFormContent.tsx [hunk 2]
```diff
@@ -0,0 +1,71 @@
...
+
+  return (
+    <S.PaymentForm ref={formRef} onSubmit={handleSubmit}>
+      <S.PaymentInput>
+        <NumberFormat
+          autoFocus
+          autoComplete="cc-number"
+          format="#### #### #### ####"
+          name="ccNumber"
+          {...basicInputProps(ccNumberText, [cardNumberError])}
```
Comment (jwm0) [inline src/@next/components/organisms/CreditCardForm/CreditCardFormContent.tsx]: As discussed, you will probably need to pass value here from Formik state. It looks like we are using 2 sources of truth here.

File: src/@next/components/organisms/CreditCardForm/stories.tsx [hunk 3]
```diff
@@ -0,0 +1,35 @@
+import { action } from "@storybook/addon-actions";
+import React from "react";
+import { CreditCardForm } from ".";
```
Comment (jwm0) [inline src/@next/components/organisms/CreditCardForm/stories.tsx]: Imports are not grouped correctly (module mixed with relative)

File: src/index.tsx [hunk 4]
```diff
@@ -14,6 +14,7 @@ import { positions, Provider as AlertProvider, useAlert } from "react-alert";
 import { ApolloProvider } from "react-apollo";
 import { render } from "react-dom";
 import { Route, Router, Switch } from "react-router-dom";
+
```
Comment (jwm0) [inline src/index.tsx]: unnecessary empty line
