### PR TITLE
Change Gotocheckout behaviour & refactor checkout

### LINKED ISSUE #217: Change gotocheckout logic
### Steps to reproduce the problem
1. Make a successful order as a logged in user
2. Try to make another and watch as the app crashes since a user is directly redirected to payment step.

This issue does not apply to orders placed as a guest.

Generally after investigating it seems that all the user information is being stored from the previous order and thus the user is directly redirected to the payment step, without the ability to chose shipping, billing data and so on.
Also, move checkout creation from `<GoToCheckout />` button to upon entering checkout. 

We need to distinguish and handle two scenarios:
1) customer will leave the checkout on a particular step, i.e. at choosing a shipping option and should be redirected back there after returning to checkout
2) customer is placing a new order and should have prefilled shipping address but should start the checkout process from the start

image

### LINKED ISSUE #224: Create checkout in API after user provides email
There is no need to create checkout objects in API if we don't have user email, as we are not able to do anything with it later. We only consider checkout to be valid if we have the email address. In order to support that, we should call the mutation to create checkout only when the user passes valid email.

### PR DESCRIPTION
**Pull request by piotrgrundas**
Refactored checkout. 
Now checkout is created after the first step - filling shipping address when the user provides a valid email. Moved it to a separate module, cleaned and improved to code, improved provider. Removed `GoToCheckout`/`GoToCart` logic.

Cart page is temporarily disabled and will be fixed in a separate ticket in #207

Resolves #224
Resolves #217

### CODE REVIEW

File: src/checkout/views/Review/View.tsx [hunk 1]
```diff
@@ -0,0 +1,120 @@
...
+  show: ShowOverlayType,
+  history: History,
+  clear: () => void
+) => {
+  const canProceed = !data.checkoutComplete.errors.length;
+
+  if (canProceed) {
+    history.push(BASE_URL);
+    clear();
+    localStorage.removeItem("cart");
```
Comment (dominik-zeglen) [inline src/checkout/views/Review/View.tsx]: TBH I'd extract all localStorage's keys to enum

File: src/checkout/views/Review/View.tsx [hunk 2]
```diff
@@ -0,0 +1,120 @@
...
+const completeCheckout = (
+  data: completeCheckout,
+  show: ShowOverlayType,
+  history: History,
+  clear: () => void
+) => {
+  const canProceed = !data.checkoutComplete.errors.length;
+
+  if (canProceed) {
+    history.push(BASE_URL);
```
Comment (dominik-zeglen) [inline src/checkout/views/Review/View.tsx]: Can we use just `<Redirect />` component to maintain consistency in project?

File: src/checkout/views/Shipping/View.tsx [hunk 3]
```diff
@@ -0,0 +1,215 @@
...
+        checkout: data.checkout,
+        step: CheckoutStep.ShippingOption
+      });
+      history.push(generatePath(shippingOptionsUrl, { token }));
+    }
+  }
+};
+
+const extractShippingData = (checkout: Checkout, shop: getShop_shop) => {
+  const hasShippingCountry = maybe(() => !!checkout.shippingAddress.country);
```
Comment (dominik-zeglen) [inline src/checkout/views/Shipping/View.tsx]: I know it's a tiny thing, but `hasShippingCountry` can be `true`, `false` or `undefined` if you use `!!` before `maybe` expression rather than before `maybe` itself.

File: src/checkout/components/AddressSummary/index.tsx [hunk 4]
```diff
@@ -1,47 +1,46 @@
...
-import { AddressInterface } from "../../core/types";
-
 import "./scss/index.scss";
 
-const AddressSummary: React.SFC<{
-  address: AddressInterface;
+import * as React from "react";
+import { getCheckout_checkout_shippingAddress } from "../../types/getCheckout";
+
+const AddressSummary: React.FC<{
```
[the remark this answers is not in the document]
Comment (piotrgrundas) [reply src/checkout/components/AddressSummary/index.tsx]:
```
    /**
     * @deprecated as of recent React versions, function components can no
     * longer be considered 'stateless'. Please use `FunctionComponent` instead.
     *
     * @see [React Hooks](https://reactjs.org/docs/hooks-intro.html)
     */
    type SFC<P = {}> = FunctionComponent<P>;

    /**
     * @deprecated as of recent React versions, function components can no
     * longer be considered 'stateless'. Please use `FunctionComponent` instead.
     *
     * @see [React Hooks](https://reactjs.org/docs/hooks-intro.html)
     */
    type StatelessComponent<P = {}> = FunctionComponent<P>;

    type FC<P = {}> = FunctionComponent<P>;
```

File: src/checkout/views/Review/View.tsx (hunk 2 above)
Comment (piotrgrundas) [reply src/checkout/views/Review/View.tsx]: I'll improve this page in #222

File: src/checkout/views/Shipping/View.tsx (hunk 3 above)
Comment (patrys) [reply src/checkout/views/Shipping/View.tsx]: `undefined` satisfies any type by default. `maybe` will fall back to `undefined` unless you provide the fallback value as the second parameter.

File: src/checkout/provider.tsx [hunk 5]
```diff
@@ -0,0 +1,91 @@
...
+
+    if (this.storedToken) {
+      return (
+        <TypedGetCheckoutQuery
+          variables={{ token: this.storedToken }}
+          onCompleted={({ checkout }) => {
+            this.setState({ checkout, loading: false });
+          }}
+        >
+          {() => provider}
```
[the remark this answers is not in the document]
Comment (piotrgrundas) [reply src/checkout/provider.tsx]: Well, `onCompleted` updates the state, and `provider` has its value from the state so really there is no need to pass data here as well.

File: src/checkout/views/Shipping/View.tsx (hunk 3 above)
Comment (piotrgrundas) [reply src/checkout/views/Shipping/View.tsx]: Looking through the definition I thought so too. Just got confused that intelisense claimed otherwise.

File: src/checkout/context.tsx [hunk 6]
```diff
@@ -0,0 +1,45 @@
+import { createContext } from "react";
+
+import { CheckoutCreateInput } from "../../types/globalTypes";
+import { Omit } from "../core/tsUtils";
+import { Checkout } from "./types/Checkout";
+import { createCheckout_checkoutCreate_errors } from "./types/createCheckout";
+
+export enum CheckoutStep {
+  ShippingAddress = "shipping Address",
```
[the remark this answers is not in the document]
Comment (piotrgrundas) [reply src/checkout/context.tsx]: Verbose logic switches in some redirects, defining what step to show etc, i.e.
https://github.com/mirumee/saleor-storefront/pull/223/files#diff-388a3f5aafa2472221f0b066b4c2a771R36
https://github.com/mirumee/saleor-storefront/pull/223/files#diff-035e102346a77e308cbfe8bc68a44d52R136
