### PR TITLE
Checkout addresses picker.

### LINKED ISSUE #241: Selecting the right address for checkout steps
### Steps to reproduce the problem
1. Add a product to bag and go to checkout as an authenticated user.
2. Fill the shipping address (note that at this point this form is empty, while we might have the default address assigned to the user) and select option `Use as Billing Address`.
image
3. Continue to the billing address step. Instead of the address from the first step, there is a different address which is assigned to my account.
image

First we should make sure that `Use as billing` checkbox actually works properly. Second, user should be able to use his default addresses that are already saved in his account. I'm not sure about the UI/UX of this - e.g. in the old storefront we show a selection of existing addresses or a form to add new address. Don't know how do we want to approach it here (question to @pwgryglak, but maybe we already have that on mockups).

### PR DESCRIPTION
**Pull request by piotrgrundas**
Resolves #241 

TODO:
- [x] fix types
- [x] style modal form
- [x] integrate with current implementation (picker should be available for logged in users only)
- [x] add to billing address

image
image

### CODE REVIEW

File: src/checkout/components/AddressPicker/Modal.tsx [hunk 1]
```diff
@@ -0,0 +1,130 @@
...
+              autoComplete="address-line1"
+            />
+            <TextField
+              label="House / Apt Number"
+              type="address-line2"
+              name="streetAddress2"
+              autoComplete="address-line2"
+            />
+            <TextField
+              label="Zip-Code"
```
Comment (NyanKiyoshi) [inline src/checkout/components/AddressPicker/Modal.tsx]:
```suggestion
              label="ZIP Code"
```

File: src/checkout/components/AddressPicker/Modal.tsx [hunk 2]
```diff
@@ -0,0 +1,130 @@
...
+            />
+            <label className="checkbox">
+              <input name="asNew" type="checkbox" />
+              <span>Use this address as new shipping address</span>
+            </label>
+          </div>
+          <div className="modal__footer">
+            <a>Cancel</a>
+            <Button type="submit" className="modal__button">
+              Ok
```
Comment (NyanKiyoshi) [inline src/checkout/components/AddressPicker/Modal.tsx]: The user is creating something when clicking the submit button, we probably should say:
```suggestion
              Add Address
```

File: src/checkout/components/AddressPicker/Picker.tsx [hunk 3]
```diff
@@ -0,0 +1,62 @@
...
+        onClick={() => onSelect(address)}
+        className={classNames("address-picker__address", {
+          "address-picker__address--selected": selectedAddress === address
+        })}
+      >
+        <AddressSummary address={address} />
+        <Option
+          selected={selectedAddress === address}
+          value={`${id}`}
+          label="Deliver to this address"
```
Comment (NyanKiyoshi) [inline src/checkout/components/AddressPicker/Picker.tsx]:
```suggestion
          label="Ship to this address"
```

File: src/checkout/components/AddressPicker/Picker.tsx [hunk 4]
```diff
@@ -0,0 +1,62 @@
...
+              overlay.show(OverlayType.modal, OverlayTheme.modal, {
+                content: (
+                  <AddNewAddressModal onAddNew={onAddNew} hide={overlay.hide} />
+                )
+              });
+            }}
+          >
+            <div>
+              <ReactSVG path={plusSvg} />
+              <p>Add new address</p>
```
Comment (NyanKiyoshi) [inline src/checkout/components/AddressPicker/Picker.tsx]: As Amazon does, we could simply say:
```suggestion
              <p>Add Address</p>
```

File: src/checkout/views/Billing/View.tsx [hunk 5]
```diff
@@ -73,61 +73,97 @@ const computeMutationVariables = (
...
+                                onChange={({ target: { checked } }) =>
+                                  this.setState({ sameAsShipping: checked })
+                                }
+                              />
+                              <span>Same as Shipping Address</span>
+                            </label>
+                          </div>
+                          <ShippingAddressForm
+                            key={`${sameAsShipping}`}
+                            buttonText="Continue to Payment"
```
Comment (NyanKiyoshi) [inline src/checkout/views/Billing/View.tsx]: Maybe it would be better to say "Proceed" instead of "Continue"? I'm not sure. 
```suggestion
                            buttonText="Proceed to Payment"
```

File: src/components/ShippingAddressForm/utils.ts [hunk 6]
```diff
@@ -0,0 +1,19 @@
...
+
+export const getFormData = (
+  geolocalization: getShop_shop_geolocalization | null,
+  defaultCountry: getShop_shop_defaultCountry | null,
+  data?: AddressType
+) =>
+  data || {
+    country: {
+      code: get(geolocalization, "country.code", defaultCountry.code),
+      country: get(geolocalization, "country.country", defaultCountry.country)
```
Comment (piotrgrundas) [inline src/components/ShippingAddressForm/utils.ts]: use `maybe()`

File: src/checkout/views/Billing/View.tsx [hunk 7]
```diff
@@ -31,103 +39,153 @@ const proceedToPayment = (
...
+                <TypedUpdateCheckoutBillingAddressMutation
+                  onCompleted={data =>
+                    proceedToPayment(data, update, history, token)
+                  }
+                >
+                  {(saveBillingAddress, { data, loading }) => (
+                    <ShopContext.Consumer>
+                      {shop => {
+                        const billingProps = {
+                          buttonText: "Continue to Payment",
```
Comment (NyanKiyoshi) [inline src/checkout/views/Billing/View.tsx]:
```suggestion
                          buttonText: "Proceed to Payment",
```

File: src/checkout/components/AddressPicker/Picker.tsx [hunk 8]
```diff
@@ -0,0 +1,86 @@
...
+    {onAddNew && (
+      <OverlayContext.Consumer>
+        {overlay => (
+          <div
+            className="address-picker__address address-picker__address--add-new"
+            onClick={() => {
+              overlay.show(OverlayType.modal, OverlayTheme.modal, {
+                content: (
+                  <Modal
+                    title="Add New Address"
```
Comment (NyanKiyoshi) [inline src/checkout/components/AddressPicker/Picker.tsx]:
```suggestion
                    title="Add Address"
```

File: src/checkout/components/AddressPicker/Picker.tsx [hunk 9]
```diff
@@ -0,0 +1,86 @@
...
+                    loading={false}
+                    formId="new-address-form"
+                    hide={overlay.hide}
+                    submitBtnText="Save"
```
Comment (NyanKiyoshi) [inline src/checkout/components/AddressPicker/Picker.tsx]:
```suggestion
                    submitBtnText="Add Address"
```

File: src/components/ShippingAddressForm/ShippingAddressForm.tsx [hunk 10]
```diff
@@ -0,0 +1,129 @@
...
+              label="State/Province"
+              type="state"
+              name="countryArea"
+              autoComplete="address-level1"
+              required
+            />
+          </div>
+          <div className="address-form__grid">
+            <TextField
+              label="Zip-Code"
```
Comment (NyanKiyoshi) [inline src/components/ShippingAddressForm/ShippingAddressForm.tsx]:
```suggestion
              label="ZIP Code"
```

File: src/components/ShippingAddressForm/ShippingAddressFormContent.tsx [hunk 11]
```diff
@@ -0,0 +1,100 @@
...
+        label="State/Province"
+        type="state"
+        name="countryArea"
+        autoComplete="address-level1"
+        required
+      />
+    </div>
+    <div className="address-form__grid">
+      <TextField
+        label="Zip-Code"
```
Comment (NyanKiyoshi) [inline src/components/ShippingAddressForm/ShippingAddressFormContent.tsx]:
```suggestion
        label="ZIP Code"
```

File: src/components/ShippingAddressForm/AddNewShippingAddressForm.tsx [hunk 12]
```diff
@@ -0,0 +1,126 @@
...
+                label="State/Province"
+                type="state"
+                name="countryArea"
+                autoComplete="address-level1"
+                required
+              />
+            </div>
+            <div className="address-form__grid">
+              <TextField
+                label="Zip-Code"
```
Comment (NyanKiyoshi) [inline src/components/ShippingAddressForm/AddNewShippingAddressForm.tsx]:
```suggestion
                label="ZIP Code"
```

**Comment by NyanKiyoshi** [comment]
Is that normal that I'm always required to give my state/province in countries that don't use that?

**Comment by NyanKiyoshi** [comment]
There is a bug, it says that I must fill the city but actually... I don't have to, I can leave it blank. Thus it breaks the continue button.

**Comment by maarcingebala** [comment]
@NyanKiyoshi Are these ⬆️ suggested text changes in accordance with our designs on Figma? We should make sure that the copy is right on mockups in the first place before we implement it.

We use [google-i18n-address](https://github.com/mirumee/google-i18n-address) for address validation, if what frontend code does is consistent with that, then it's fine. Otherwise, we have a bug.

**Comment by AlicjaSzu** [comment]
> There is a bug, it says that I must fill the city but actually... I don't have to, I can leave it blank. Thus it breaks the continue button.

City should be required, it's a bug.

**Comment by NyanKiyoshi** [comment]
>We use google-i18n-address for address validation, if what frontend code does is consistent with that, then it's fine. Otherwise, we have a bug.

In France we do not have those, the storefront 1.0 handles the case.

**Comment by NyanKiyoshi** [comment]
> @NyanKiyoshi Are these ⬆️ suggested text changes in accordance with our designs on Figma? We should make sure that the copy is right on mockups in the first place before we implement it.

@maarcingebala the ZIP code shouldn't be `Zip-code` yes.

I feel like the modal for adding a new address shouldn't have "Save" as primary button. But "Add [Address]", it doesn't make sense to me to "Save" something that doesn't exist yet. I'm unsure whether this change would be willing to be taken into consideration.

For the "Add New Address" the word "New" is just redundant. Unless we change it to "Add a new address"

File: src/checkout/components/AddressPicker/Picker.tsx [hunk 13]
```diff
@@ -0,0 +1,84 @@
...
+    <AddNewShippingAddressForm
+      billing={billing}
+      loading={loading}
+      errors={errors}
+      onSubmit={handleAddressAdd}
+    />
+  </Modal>
+);
+
+const AddressPicker: React.SFC<IAddressPickerProps> = props => (
```
Comment (piotrgrundas) [inline src/checkout/components/AddressPicker/Picker.tsx]: `React.FC`

File: src/checkout/components/GuestAddressForm/GuestAddressForm.tsx [hunk 14]
```diff
@@ -0,0 +1,109 @@
...
+const GuestAddressForm: React.SFC<IGuestAddressProps> = ({
+  buttonText,
+  checkout,
+  errors,
+  loading,
+  onSubmit,
+  proceedToNextStep,
+  shippingAsBilling,
+  shop,
+  type = "shipping"
```
Comment (piotrgrundas) [inline src/checkout/components/GuestAddressForm/GuestAddressForm.tsx]: I would consider making it an enum.

File: src/checkout/views/Billing/Page.tsx [hunk 15]
```diff
@@ -0,0 +1,168 @@
...
+    }
+  };
+};
+
+class View extends React.Component<IBillingPageProps, IBillingPageState> {
+  readonly state = {
+    checkout: null,
+    errors: [],
+    loading: false
+  };
```
Comment (piotrgrundas) [inline src/checkout/views/Billing/Page.tsx]: Consider switching to hooks

File: src/components/ShippingAddressForm/AddNewShippingAddressForm.tsx [hunk 16]
```diff
@@ -0,0 +1,120 @@
...
+import { getFormData } from "./utils";
+
+export const AddNewShippingAddressForm: React.SFC<
+  IShippingNewAddressFormProps
+> = ({ data, billing, errors, onSubmit, children }) => (
+  <div className="address-form">
+    <ShopContext.Consumer>
+      {({ countries, geolocalization, defaultCountry }) => {
+        const checkboxText = billing
+          ? "Use this address as new billing address"
```
Comment (piotrgrundas) [inline src/components/ShippingAddressForm/AddNewShippingAddressForm.tsx]: U could just toggle `billing`, `shipping` word

File: src/checkout/views/Billing/Page.tsx (hunk 15 above)
Comment (AlicjaSzu) [reply src/checkout/views/Billing/Page.tsx]: i'd love to, but at first we need to bump up version of react

File: CHANGELOG.md [hunk 17]
```diff
@@ -19,6 +19,8 @@ All notable, unreleased changes to this project will be documented in this file.
 - Add order confirmation page - #263 by @piotrgrundas
 - Fix checkout composition - #264 by @piotrgrundas
 - Fix rendering order statuses and order line prices - #281 by @maarcingebala
+- Add ability to select user stored addresses, update copying shipping address to billing - #265 by @piotrgrundas
+- Fix rendering order statuses and order line prices - #281 by @maarcingebala
```
[the remark this answers is not in the document]
Comment (AlicjaSzu) [reply CHANGELOG.md]: fixed
