### PR TITLE
Ordinary conditional checks when no data exist to make storefront works

### LINKED ISSUE #508: saleor-storefront doesn't work without data in saleor database
### What I'm trying to achieve
When there is no data in saleor database saleor-storefront doesn't work. 

### Steps to reproduce the problem
1. Install saleor but skip step with 'populatedb'. 
2. Run saleor-storefront on your machine

### What I expected to happen
I expect that saleor-storefront works even without data in saleor database.

### PR DESCRIPTION
**Pull request by orzechdev**
I want to merge this change because it should fix #508. 

### Screenshots

When no data exist in the database:

Zrzut ekranu 2019-12-27 o 17 53 24

### Pull Request Checklist

1. [x] All visible strings are translated with proper context.
1. [x] All data-formatting is locale-aware (dates, numbers, and so on).
1. [x] The changes are tested.
1. [x] The code is documented (docstrings, project documentation).
1. [x] Changes are mentioned in the changelog.

### CODE REVIEW

File: src/views/Home/View.tsx [hunk 1]
```diff
@@ -15,17 +15,21 @@ const View: React.FC = () => (
   <div className="home-page">
     <TypedHomePageQuery alwaysRender displayLoader={false} errorPolicy="all">
       {({ data, loading }) => {
-        if (canDisplay(data)) {
+        if (canDisplay(data) || true) {
```
Comment (tomaszszymanski129) [inline src/views/Home/View.tsx]: if that really was the intention here, `if` can be removed as the statement content will always be truthy.

Comment (orzechdev) [reply src/views/Home/View.tsx]: no... its the mistake, i'll change it
