### PR TITLE
Fix invalid handling of checkouts without shipping

### LINKED ISSUE #258: Checkout for digital products
Implement a checkout flow for digital products. In this flow we don't need to gather information related to shipping such as shipping address or shipping method. There shuold be three steps:
1) Billing address
2) Payment
3) Order review

There are two ways to determine whether shipping is required:
- at the product level - this will be probably used at the local cart level or before we create checkout in the API:
```graphql
product(id: $id) {
  productType {
    isShippingRequired
  }
}
```

- Once a checkout instance is created in the API we can fetch it from `Checkout` type:
```graphql
checkout {
  isShippingRequired
}
```

### LINKED ISSUE #400: Invalid handling of checkouts without shipping
### What I'm trying to achieve
Order products that have no shipping.

### Steps to reproduce the problem
1. Add a product without shipping (books, digital, etc.)
2. Try to complete the checkout
3. It will fail

### What I expected to happen
1. Not to be able to add a shipping address
1. Not to be able to select a shipping method

### Notes
This is related and blocked by https://github.com/mirumee/saleor/issues/4321.

### LINKED ISSUE #541: Checkout with digital product and removed physical product
### What I'm trying to achieve
Create checkout.
Checkout lines add/update/delete can change selected shipping method in checkout. We should synchronise shipping method with backend.

### Steps to reproduce the problem
1. Add shippable product
2. Add non-shippable product
4. Add shipping method
3. Remove all shippable product, left an only non-shippable product
4. Shipping method doesn't exist on backend side but storefront doesn't refresh checkout.

### PR DESCRIPTION
**Pull request by orzechdev**
Changes:
- In general, make checkout working without shipping if it is not required.
- Fix #258 
- Fix #400 
- Fix #541 

Notion:
- Updated graphql dependency due to `Error: Cannot find module 'graphql/validation/rules/PossibleTypeExtensions'` when `apollo codegen:generate --target=typescript types` executed.

Refactor (tldr: redirection and determination of checkout route is moved to a higher position in the components hierarchy):
- Create `useCheckoutStepState()` hook to handle state of step and removed step out of checkout context - it should not be there as there it is not connected with context, step state is just memoization of step, where the user left his/her work. Moreover step state now can depend on other contexts and data, so it is not tight coupled with checkout context anymore.
- Remove `StepCheck` out of checkout pages - the logic of redirection to prevent user from entering invalid step by manually pasting the url is moved to main `index.js` of checkout, i.e. `CheckoutApp`.
- Refactor `CheckoutDispatcher` and move it to `routes` directory as `CheckoutRouteDispatcher`.

### Pull Request Checklist

1. [x] All visible strings are translated with proper context.
1. [x] All data-formatting is locale-aware (dates, numbers, and so on).
1. [x] The changes are tested.
1. [x] The code is documented (docstrings, project documentation).
1. [x] Changes are mentioned in the changelog.

### CODE REVIEW

File: src/checkout/hooks/useCheckoutStepState.ts [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+}
+
+export const useCheckoutStepState = (
+  checkout: Checkout,
+  variantsProducts: VariantsProducts_productVariants,
+  cardData: CardData,
+  dummyStatus: string
+): CheckoutStep => {
+  const isShippingRequiredForProducts = () => {
+    const isShippingRequired =
```
Comment (mateuszkula) [inline src/checkout/hooks/useCheckoutStepState.ts]: I think this can be simplified to just
```
return variantsProducts.edges && variantsProducts.edges.some(
        ({ node }) => node.product.productType.isShippingRequired
);
```

If there are no `edges` we will get false, and `some` is returning Boolean so we dont need temp variable for keeping the result

Comment (orzechdev) [reply src/checkout/hooks/useCheckoutStepState.ts]: Sure, fixed
